### ISSUE TITLE
Adding .update() func to neoscore.py

### ISSUE THREAD

**Issue by craigvear** [DigiScore/neoscore#111]
Could we add a method for refreshing neoscore ui as an update call? 

At the moment we have .show() and .refresh_func(), both of which setup an independent thread/ cycle within QT. However, when integrating neoscore into larger, complex projects we may wish to offer the refresh rate to be dependent, and driven by another function or library (as I do now): midi playback ticks

**Comment by ajyoon** [comment]
Hey Craig, thanks for the suggestion! This sort of behavior is already supported, although it's not obvious how.  Neoscore events can be driven by external processes using standard interprocess-communication techniques. For example, we can run a simple HTTP server in a separate thread alongside Neoscore; the server can then receive commands via network requests (including localhost), then store those commands in some shared state, and have Neoscore check for changes in that state on every refresh. This approach could just as easily be applied to a thread which listens for MIDI events or whatever you want.

We could consider making an explicit 'update' function, but the implementation would work just like this under the hood. We plug our refresh functions into the Qt runtime using a callback method; we request Qt call our function for us at regular intervals. Qt is always running at its own internal refresh rate, we just make it *look* like we're controlling the clock.

```python
import threading
from flask import Flask  # pip install flask

from neoscore.core import neoscore
from neoscore.core.text import Text
from neoscore.core.point import ORIGIN


neoscore.setup()

# This holds our shared state; for more serious applications a queue.Queue should be used instead
message = None
# Example Neoscore object to change based on messages
text = Text(ORIGIN, None, 'Send request to change this text')


def refresh_func(time) -> neoscore.RefreshFuncResult:
    global message
    trigger_render = False
    if message:
        # Trigger re-render
        text.text = message
        message = None
        trigger_render = True
    return neoscore.RefreshFuncResult(trigger_render)


# Set up Flask server to receive messages from other processes
app = Flask(__name__)

@app.route('/<msg>')
def endpoint(msg):
    global message
    message = msg
    return f'Requested Neoscore change text to: {msg}'

def run_app():
    app.run()

# Make sure to run Flask in another thread because we still
# need to give the main thread to Neoscore/QT
thread = threading.Thread(target=run_app)
thread.start()

# Now start up Neoscore
neoscore.show(refresh_func)
```

![demo](https://github.com/DigiScore/neoscore/assets/15976214/550fd3fa-d537-4f37-a63a-1ea7e5fb0cc4)

**Comment by craigvear** [comment]
Thank you Andrew - and HNY!!.

Nice code. I'll have a look at implementing this in my project.

bw
c
