### ISSUE TITLE
Create convenience class for ties

### ISSUE THREAD

**Issue by ajyoon** [DigiScore/neoscore#22]
We already support ties via the `Slur` class, but users do need to be careful to make sure that this tie stays horizontal. We can make this easier for users by creating a dedicated `Tie` class which automatically enforces horizontal-ness and asks users to only provide an `end_x` instead of `end_pos`. 

Unfortunately, I don't think something as simple as this would work:

```python
class Tie(Slur, Spanner):
    ...
```

because I think it would run into multiple-inheritance issues (since `Slur` extends `Spanner2D` which extends `Spanner`). I think the required solution would be something like:

```python

class AbstractSlur():
    @staticmethod
    def draw_slur(params) -> Path
        ...

class Tie(AbstractSlur, Spanner):
    ...

class Slur(AbstractSlur, Spanner2D):
    ...

```

**Comment by craigvear** [comment]
Hi Andrew. I’ll give this a go. Is the solution above still the feasible way forward?

**Comment by ajyoon** [comment]
I think so, yeah. Technically it's a breaking change but it's minor and I think worthwhile. btw if it's not clear, my idea is for those 3 classes to be in separate files.

**Comment by ajyoon** [comment]
The best model for this pattern is `AbstractStaff`, which works in much the same way. Similarly I would recommend making `AbstractSlur` inherit `PaintedObject` and `HasMusicFont` as well to minimize code duplication between `Slur` and `Tie`.

**Comment by craigvear** [comment]
Very clear as always.  Will chip away at it over the coming week.

**Comment by craigvear** [comment]
just having a first tinker now. Am I correct in thinking that AbstractSlur will work on positioned objects side of the common calculation, then Slur or Tie will deal with the end coords with spanner or Spanner2D?

**Comment by ajyoon** [comment]
right, and `AbstractSlur` will provide a common method for drawing the path, which `Slur` and `Tie` will each invoke. `AbstractSlur` doesn't need to have an appearance of its own since it's an abstract class not meant to be created on its own.

**Comment by craigvear** [comment]
If so then the main method in AbstractSlur, probably isn't "def draw_slur", but more like "def start_slur"???

Also, will the return for this func be a MusicFont.

**Comment by ajyoon** [comment]
no, `AbstractSlur` can draw the entire shape using a static method that takes all the parameters needed to draw it

**Comment by craigvear** [comment]
just sent PR. Instead of using Spanner for tie and Spanner2D for Slur, I used Spanner2D for both - Tie still only requires end_x.

**Comment by craigvear** [comment]
Is this closed?

**Comment by ajyoon** [comment]
yep
