### ISSUE TITLE
Investigate whether other music fonts work

### ISSUE THREAD

**Issue by ajyoon** [DigiScore/neoscore#29]
In theory we should support any SMuFL-compliant music font, but we've only ever worked with and tested against Bravura. We should try out some other fonts and see what breaks.

**Comment by craigvear** [comment]
https://github.com/fkretlow/sebastian sebastian (Bach) looks like a good one to test.

**Comment by ajyoon** [comment]
music fonts can be registered with [`neoscore.register_music_font`](https://neoscore.org/api/neoscore.core.neoscore.html#neoscore.core.neoscore.register_music_font)

**Comment by jgarte** [comment]
@ajyoon 

Should [tests](https://github.com/DigiScore/neoscore/blob/main/tests/test_core/test_font.py) be written for each SMuFL-compliant music font?

**Comment by ajyoon** [comment]
I don't think so, unless we want to bundle the new font in the repo. I'm open to it, but only if user demand is enough to warrant increasing the package size. This ticket is more about manually testing out examples with other SMuFL-compliant fonts and seeing if anything breaks or looks wrong. I expect bugs would surface and we'd want to spin off separate issues for this.

That said, I think @craigvear has been chipping away at this, so if you want to take a crack at it we should confirm with him first. Craig, what do you think?

**Comment by jgarte** [comment]
@craigvear @ajyoon 

* What are the steps involved in properly testing other music fonts?
* How many do we want to test in total in order to close this issue?

**Comment by ajyoon** [comment]
We might want to consider adding a way to globally change the default music font (maybe the global default text font too), but that would be a separate ticket down the line too.

**Comment by Xavman42** [comment]
Just noticed that there are some clipping issues with the Bravura font when used in a Text object: 
![image](https://user-images.githubusercontent.com/79334532/210184542-463cc217-236e-4aeb-a2b3-ecee18460379.png)

Here's the code used to generate this image:
```
from neoscore.common import *

neoscore.setup()

lowercase_alphabet = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
                      "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
uppercase_alphabet = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M",
                      "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]
numbers = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]
other = ["`", "~", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "-", "_", "=", "+", "[", "{", "]", "}", ";", ":",
         "'", "\"", ",", "<", ".", ">", "/", "?", "\\", "|"]

for index, text in enumerate(lowercase_alphabet):
    Text((Unit(0), Unit(index*10)), None, text, Font("Bravura", (index % 7)+5))

for index, text in enumerate(uppercase_alphabet):
    Text((Unit(20), Unit(index*10)), None, text, Font("Bravura", (index % 7)+5))

for index, text in enumerate(numbers):
    Text((Unit(40), Unit(index*10)), None, text, Font("Bravura", (index % 7)+5))

for index, text in enumerate(other):
    Text((Unit(60), Unit(index*10)), None, text, Font("Bravura", (index % 7)+5))

neoscore.set_viewport_scale(8)
neoscore.show()

```

**Comment by ajyoon** [comment]
Thanks for reporting that, I've noticed similar issues with other fonts and plaint `Text` objects before too. If I remember right, the issue affects different environments differently since it relies on low-level text layout systems. I'll try to take a look this week.

**Comment by ajyoon** [comment]
I built a little example demonstrating this capability and tested it locally. I found one small bug and fixed it in the above commit.

Sebastian: 
![sebastian](https://user-images.githubusercontent.com/15976214/218641387-48e545ef-81a8-4371-8029-a63acbe79abf.png)

Bravura: 
![bravura](https://user-images.githubusercontent.com/15976214/218641389-b80aff81-bd63-40c1-aec3-57fb1f84c51f.png)
 (don't mind the broken trill appearance, that's because I used the wrong glyph for it)
