### ISSUE TITLE
`Text` which starts or ends with whitespace is clipped incorrectly

### ISSUE THREAD

**Issue by ajyoon** [DigiScore/neoscore#34]
If the string given to a `Text` starts or ends in whitespace, it is clipped on the opposite side by the whitespace width. This is a funny consequence of the way neoscore renders text - internally it converts it to a Qt path, and that path's bounding rect is used in working out clip geometry. When a string has leading or trailing whitespace, its logical object bounding rect does not actually match the underlying patch bounding rect, so the rendered path is clipped incorrectly. This occurs even when the `Text` object is not breakable.

Demonstration (running with `NEOSCORE_DEBUG=1` so Qt bounding rects are shown):

```python
Text(ORIGIN, None, "  test")
```

![clipped](https://user-images.githubusercontent.com/15976214/168449536-85e82d3d-07a7-4149-b7b1-dd5e4a4cb994.png)

This is somewhat related to #21 in how it is caused by bad assumptions in the path rendering pipeline.

**Comment by Xavman42** [comment]
Looks like this issue may have been resolved in issue #93. `Text(ORIGIN, None, "  test")` now produces the following image on my Ubuntu machine:
![image](https://user-images.githubusercontent.com/79334532/211048061-41e3f4d4-79cf-4845-bc7d-fd422d53d0d4.png)
