### ISSUE TITLE
PyQT issue for install  neoscore on a Raspberry Pi running Raspbian v10 (buster)

### ISSUE THREAD

**Issue by craigvear** [DigiScore/neoscore#48]
Hi, I'm trying to install neoscore on a Raspberry Pi running Raspbian v10 (buster).  I'm getting exactly the same error(s) as above and I've tried most of the above suggestions, except, of course, that I have no Rosetta to run from!  Is there anything that I can do to progress?  I have, incidentally, managed to get neoscore working on a Mac running 10.13.6.

_Originally posted by @richardhoadley in https://github.com/DigiScore/neoscore/discussions/35#discussioncomment-3004382_

**Comment by craigvear** [comment]
Hi Andrew. I’ve migrated this issue by Richard to a new thread.

**Comment by ajyoon** [comment]
@richardhoadley we just release neoscore 0.1.3, which reduces the minimum required python version to 3.7. This should allow you to use the prebuilt PyQt5 wheels. Could you try installing neoscore again on Python 3.7 and let us know if it works?

**Comment by ajyoon** [comment]
Closing this now on the assumption the prebuilt wheels work. We can reopen later if this turns out to not be the case.
