### ISSUE TITLE
[Feature Request] Click on images in documentation to see full code

### ISSUE THREAD

**Issue by kitchWWW** [DigiScore/neoscore#60]
One of the features of the lilypond documentation that I absolutely love is that every score, you can click on and it'll show you the full source code required to make the image. I would love to click on the image on the home page
https://neoscore.org/index.html
of the documentation and see the source code required to make it.

**Comment by ajyoon** [comment]
Thanks for the suggestion! It's live now. I believe all the other example images have their source code in blocks just above them.
