### ISSUE TITLE
pedal_line TypeError for None half lift positions

### ISSUE THREAD

**Issue by craigvear** [DigiScore/neoscore#75]
When calling pedal_line without half lift positions I get this error:

line 85, in _draw_path
    for pos in self.half_lift_positions:
TypeError: 'NoneType' object is not iterable

The associated code is
# Draw half lift positions, if any exist
        for pos in self.half_lift_positions:
            if isinstance(pos, tuple):

**Comment by craigvear** [comment]
Am getting the following error when I run any test involving Staff() including my new test for pedal_line


============================= test session starts ==============================
collecting ... 
tests/test_western/test_staff.py:None (tests/test_western/test_staff.py)
tests/test_western/test_staff.py:4: in <module>
    from neoscore.core.flowable import Flowable
neoscore/core/flowable.py:8: in <module>
    from neoscore.core.layout_controllers import MarginController, NewLine
neoscore/core/layout_controllers.py:4: in <module>
    from neoscore.core.page import Page
neoscore/core/page.py:5: in <module>
    from backports.cached_property import cached_property
E   ModuleNotFoundError: No module named 'backports'

tests/test_western/test_staff.py:None (tests/test_western/test_staff.py)
ImportError while importing test module '/Users/craigvear/PycharmProjects/neoscore/tests/test_western/test_staff.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../Library/Caches/pypoetry/virtualenvs/neoscore-Y5fKZ6nG-py3.10/lib/python3.10/site-packages/_pytest/python.py:608: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
../../Library/Caches/pypoetry/virtualenvs/neoscore-Y5fKZ6nG-py3.10/lib/python3.10/site-packages/_pytest/pathlib.py:533: in import_path
    importlib.import_module(module_name)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
../../Library/Caches/pypoetry/virtualenvs/neoscore-Y5fKZ6nG-py3.10/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:168: in exec_module
    exec(co, module.__dict__)
tests/test_western/test_staff.py:4: in <module>
    from neoscore.core.flowable import Flowable
neoscore/core/flowable.py:8: in <module>
    from neoscore.core.layout_controllers import MarginController, NewLine
neoscore/core/layout_controllers.py:4: in <module>
    from neoscore.core.page import Page
neoscore/core/page.py:5: in <module>
    from backports.cached_property import cached_property
E   ModuleNotFoundError: No module named 'backports'






collected 0 items / 2 errors

ERROR: not found: /Users/craigvear/PycharmProjects/neoscore/tests/test_western/test_staff.py::TestStaff::test_allows_pen_override
============================== 2 errors in 0.35s ===============================
(no name '/Users/craigvear/PycharmProjects/neoscore/tests/test_western/test_staff.py::TestStaff::test_allows_pen_override' in any of [<DoctestModule tests/test_western/test_staff.py>, <Module tests/test_western/test_staff.py>])


Process finished with exit code 4

**Comment by craigvear** [comment]
also - updated requirements from poetry.lock are failing.

**Comment by ajyoon** [comment]
If you're seeing errors like that, your environment is not set up correctly. Sounds like the dependencies are not installed properly. What do you mean about poetry.lock errors? Could you share the error in question?

**Comment by craigvear** [comment]
Agreed. I’ll delete and rebuild from scratch.

**Comment by craigvear** [comment]
clean install. re did poetry in terminal. followed instructions. error report:

Traceback (most recent call last):
  File "/Users/craigvear/PycharmProjects/neoscore/examples/kitchen_sink.py", line 13, in <module>
    from neoscore.core.flowable import Flowable
  File "/Users/craigvear/PycharmProjects/neoscore/neoscore/core/flowable.py", line 8, in <module>
    from neoscore.core.layout_controllers import MarginController, NewLine
  File "/Users/craigvear/PycharmProjects/neoscore/neoscore/core/layout_controllers.py", line 4, in <module>
    from neoscore.core.page import Page
  File "/Users/craigvear/PycharmProjects/neoscore/neoscore/core/page.py", line 5, in <module>
    from backports.cached_property import cached_property
ModuleNotFoundError: No module named 'backports'

**Comment by craigvear** [comment]
hmmm - clean install from scratch including poetry and all updates in brew, pycharm. 

got error in poetry install:

Installing lxml (4.9.1): Failed
...
note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for lxml

**Comment by ajyoon** [comment]
What's the lxml error? maybe try with python 3.7?

**Comment by craigvear** [comment]
yeah - 3.7 works on my Mac (which is odd as first time round 3.10 was fine).
